### ISSUE TITLE
Scroll or other feature when long categories

### ISSUE THREAD

**Issue by joehigab** [nishantjainuk/SimpleWaterfall-PowerBI#5]
Hi, 
first thanks a lot for the waterfall chart it is really useful. 

is it possible to add a scroll feature to the chart whenever the visualization can't fit within the boundaries of the x axis. I have long categories and the chart is not readable. 
another way is to show a new sentiment that aggregates all small categories in a field called others.

thanks alot
/jawdat

**Comment by joehigab** [comment]
Hi Nishan! thanks a lot in advance for taking this into consideration!

**Comment by nishantjainuk** [comment]
I expect the scrollable version to be available in the next version. Expect it to be released by end of Jan 2020.

**Comment by joehigab** [comment]
Great! Thanks alot. Please also feel free to notify me once released! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nishantjainuk** [comment]
@joehigab 

I have created the beta version for you to test the scrollable version. You can download it from [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Simple%20Waterfall%20(beta%202.0.4).pbiviz)

To make the visual scrollable, switch off the property "fit to width" in the "X-axis" section of the properties pane. You can also change the size of the bars if you want. 

There are some new features in the visual. You can find the full list [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Version%20History.md). 

I would appreciate if you could provide any issues / bugs for this new version. I would submit the new version to Microsoft next week and would appreciate your feedback for any bugs so that I can fix them before submission. 

Thanks

**Comment by nishantjainuk** [comment]
@joehigab 

I have added a new option as per your suggestion. Now you can choose when to fix the X-axis with the width of the visual or want it scrollable

To enable the scrollable option, switch off the option highlighted below. 

![image](https://user-images.githubusercontent.com/24504997/75113298-86598500-5644-11ea-8dca-ba81008c82a2.png)


I have submitted the visual to Microsoft and it can upto 3 weeks for the changes to reflect in the appsource. Until then, you can download the beta version [here](https://github.com/nishantjainuk/SimpleWaterfallPBI/blob/master/Simple%20Waterfall%20(beta%202.0.4).pbiviz?raw=true).

You can load this beta version and try it.

Note that you will have to remove the beta version and use the appsource version once it is live.

Looking forward for your feedback

**Comment by joehigab** [comment]
Hi @nishantjainuk  thanks for the new feature it is really good and as described. however, now as I am using waterfalls more and more, I think fitting the chart to the width and grouping all small categories in others is the best way to see waterfalls. say display top 15 deviations including an "other".

but anyway thanks alot for the feature. 👍

**Comment by nishantjainuk** [comment]
@joehigab This feature is now live in the latest version 2.10.0.1
