### ISSUE TITLE
Label Format "none" shows strange results

### ISSUE THREAD

**Issue by stephanbab** [nishantjainuk/SimpleWaterfall-PowerBI#51]
I would like to display my data labels in normal units i.e. not in Thousands, Billions and so on. Whenever I select "None" I only get strangely formated labels and cannot even adjust the decimal places: 

![Label issue](https://user-images.githubusercontent.com/79588784/109017558-953fa100-76b7-11eb-973e-a303e4ba414a.png)

**Comment by nishantjainuk** [comment]
@stephanbab 

When you select "None", the visual uses the format defined in your model. I guess in your case the format has not been defined or it is currently marked as "General". If you change your measures format to show 2 decimal places,  the visual will show 2 decimal places

The reason you can't select decimal places when you select "none" as the option is because "None" allows you to use your own format including the decimal places. I hope this helps

Thanks

**Comment by stephanbab** [comment]
Many Thanks for the prompt response which solved my issue!
